// ISO-3166-1 alpha-2 → Hemisphere Map
// north  = Entirely or primarily in Northern Hemisphere
// south  = Entirely or primarily in Southern Hemisphere
// equator = Straddles the equator or lies extremely close

const hemisphereMap = {
  AF: 'north',
  AX: 'north',
  AL: 'north',
  DZ: 'north',
  AS: 'south',
  AD: 'north',
  AO: 'south',
  AI: 'north',
  AQ: 'south',
  AG: 'north',
  AR: 'south',
  AM: 'north',
  AW: 'north',
  AU: 'south',
  AT: 'north',
  AZ: 'north',

  BS: 'north',
  BH: 'north',
  BD: 'north',
  BB: 'north',
  BY: 'north',
  BE: 'north',
  BZ: 'north',
  BJ: 'north',
  BM: 'north',
  BT: 'north',
  BO: 'south',
  BQ: 'north',
  BA: 'north',
  BW: 'south',
  BV: 'south',
  BR: 'south',
  IO: 'south',
  BN: 'north',
  BG: 'north',
  BF: 'north',
  BI: 'south',

  KH: 'north',
  CM: 'equator',
  CA: 'north',
  CV: 'north',
  KY: 'north',
  CF: 'north',
  TD: 'north',
  CL: 'south',
  CN: 'north',
  CX: 'south',
  CC: 'south',
  CO: 'equator',
  KM: 'south',
  CD: 'equator',
  CG: 'equator',
  CK: 'south',
  CR: 'north',
  CI: 'north',
  HR: 'north',
  CU: 'north',
  CW: 'north',
  CY: 'north',
  CZ: 'north',

  DK: 'north',
  DJ: 'north',
  DM: 'north',
  DO: 'north',

  EC: 'equator',
  EG: 'north',
  SV: 'north',
  GQ: 'equator',
  ER: 'north',
  EE: 'north',
  SZ: 'south',
  ET: 'north',

  FK: 'south',
  FO: 'north',
  FJ: 'south',
  FI: 'north',
  FR: 'north',

  GF: 'north',
  PF: 'south',
  TF: 'south',

  GA: 'equator',
  GM: 'north',
  GE: 'north',
  DE: 'north',
  GH: 'north',
  GI: 'north',
  GR: 'north',
  GL: 'north',
  GD: 'north',
  GP: 'north',
  GU: 'north',
  GT: 'north',
  GG: 'north',
  GN: 'north',
  GW: 'north',
  GY: 'north',

  HT: 'north',
  HM: 'south',
  VA: 'north',
  HN: 'north',
  HK: 'north',
  HU: 'north',

  IS: 'north',
  IN: 'north',
  ID: 'equator',
  IR: 'north',
  IQ: 'north',
  IE: 'north',
  IM: 'north',
  IL: 'north',
  IT: 'north',

  JM: 'north',
  JP: 'north',
  JE: 'north',
  JO: 'north',

  KZ: 'north',
  KE: 'equator',
  KI: 'equator',
  KP: 'north',
  KR: 'north',
  KW: 'north',
  KG: 'north',

  LA: 'north',
  LV: 'north',
  LB: 'north',
  LS: 'south',
  LR: 'north',
  LY: 'north',
  LI: 'north',
  LT: 'north',
  LU: 'north',

  MO: 'north',
  MG: 'south',
  MW: 'south',
  MY: 'equator',
  MV: 'north',
  ML: 'north',
  MT: 'north',
  MH: 'north',
  MQ: 'north',
  MR: 'north',
  MU: 'south',
  YT: 'south',
  MX: 'north',
  FM: 'north',
  MD: 'north',
  MC: 'north',
  MN: 'north',
  ME: 'north',
  MS: 'north',
  MA: 'north',
  MZ: 'south',
  MM: 'north',

  NA: 'south',
  NR: 'south',
  NP: 'north',
  NL: 'north',
  NC: 'south',
  NZ: 'south',
  NI: 'north',
  NE: 'north',
  NG: 'north',
  NU: 'south',
  NF: 'south',
  MP: 'north',
  NO: 'north',

  OM: 'north',

  PK: 'north',
  PW: 'north',
  PS: 'north',
  PA: 'north',
  PG: 'south',
  PY: 'south',
  PE: 'south',
  PH: 'north',
  PN: 'south',
  PL: 'north',
  PT: 'north',
  PR: 'north',
  QA: 'north',

  RE: 'south',
  RO: 'north',
  RU: 'north',
  RW: 'south',

  BL: 'north',
  SH: 'south',
  KN: 'north',
  LC: 'north',
  MF: 'north',
  PM: 'north',
  VC: 'north',
  WS: 'south',
  SM: 'north',
  ST: 'equator',
  SA: 'north',
  SN: 'north',
  RS: 'north',
  SC: 'south',
  SL: 'north',
  SG: 'equator',
  SX: 'north',
  SK: 'north',
  SI: 'north',
  SB: 'south',
  SO: 'north',
  ZA: 'south',
  GS: 'south',
  SS: 'north',
  ES: 'north',
  LK: 'north',
  SD: 'north',
  SR: 'north',
  SJ: 'north',
  SE: 'north',
  CH: 'north',
  SY: 'north',

  TW: 'north',
  TJ: 'north',
  TZ: 'equator',
  TH: 'north',
  TL: 'south',
  TG: 'north',
  TK: 'south',
  TO: 'south',
  TT: 'north',
  TN: 'north',
  TR: 'north',
  TM: 'north',
  TC: 'north',
  TV: 'south',

  UG: 'equator',
  UA: 'north',
  AE: 'north',
  GB: 'north',
  US: 'north',
  UM: 'north',
  UY: 'south',
  UZ: 'north',

  VU: 'south',
  VE: 'north',
  VN: 'north',
  VG: 'north',
  VI: 'north',

  WF: 'south',
  EH: 'north',

  YE: 'north',
  ZM: 'south',
  ZW: 'south'
};

export default hemisphereMap;
